[package]
name = "bplay-jit"
version = "0.1.0"
edition = "2024"
rust-version = "1.88.0"
license = "MIT"

[dependencies]
rodio = { version = "0.21.1", default-features = false, features = ["mp3", "playback"]}
ctrlc = { version = "3.2.3", default-features = false }
crossterm = "0.29.0"
user_dirs = "0.2.0"
reqwest = { version = "0.13.5", features = ["blocking"] }
indicatif = "0.18.6"
which = "8.0.6"
libasciic = { version = "1.1.2", default-features = false }

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["consoleapi","processenv","winbase","wincon","handleapi"] }
